export const MAKE_TEAM_INTERESTED_IN_PLAYER = 'freeMarket/MAKE_TEAM_INTERESTED_IN_PLAYER';
export const MAKE_TEAM_UNINTERESTED_IN_PLAYER = 'freeMarket/MAKE_TEAM_UNINTERESTED_IN_PLAYER';
export const REMOVE_PLAYER_FROM_INTERESTED = 'freeMarket/REMOVE_PLAYER_FROM_INTERESTED';
export const ADD_TEAM_TO_TRANSFERRED = 'freeMarket/ADD_TEAM_TO_TRANSFERRED';
export const RESET_WHOLE_MARKET = 'freeMarket/RESET_WHOLE_MARKET';
